### ISSUE TITLE
Visual editor error

### ISSUE THREAD

**Issue by Hazzel1337** [kivy-garden/garden.rotabox#2]
When i load an image, it first works fine, when i than try to click on it or do auto bound it says:
    
 raise EOFError('Image data is missing, make sure that image is'
 EOFError: Image data is missing, make sure that image isloaded with keep_data=True keyword.

when i look true the code of the rotabox.py, it looks like keep_data= True is used, so no clue whats the real issue

**Comment by unjuan** [comment]
The image needs to be a png file.
If it is, I will need more details (or the image)

**Comment by Hazzel1337** [comment]
![Ship1](https://user-images.githubusercontent.com/86962268/140615305-6ef8577f-f06c-4eb5-84a7-66dfcd07fb6a.png)

i get the same error with the included grid.png image

**Comment by Hazzel1337** [comment]
the image seem to not keep the alpha channel, doesnt matter where i upload it, here or imgur, but as i said above i get same error with the included grid.png image

**Comment by unjuan** [comment]
Your image works fine here and I can't replicate the problem...
So the error on clicking on the image occurs in the editor, before you get in the Auto Bounds mode?
If yes, what do you mean "it first works fine"?
Are you using kivy 1.10.0?

**Comment by Hazzel1337** [comment]
if i click on the image or on the auto bounds button, on both occasion it gives the error. i am using the newst version, which is 2.0.0.

**Comment by unjuan** [comment]
I opened an issue for the matter:
https://github.com/kivy/kivy/issues/7680#issue-1047723565
Regardless, I'll upload a Rotabox update (with a temporary fix) soon.

**Comment by unjuan** [comment]
Rotabox updated (and fixed for now)!

**Comment by Hazzel1337** [comment]
Thank you ! <3
